version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - fonts-noto-cjk
    - texlive-xetex
    - texlive-lang-chinese

sphinx:
  configuration: source/conf.py

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
